### ISSUE TITLE
[x/programs] Put all `Debug` implementations behind a `debug` feature flag for the `wasmlanche-sdk`

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/hypersdk#1031]
We should minimize the work for the compiler and make sure we aren't compiling extra code for actual deployments. Using a feature flag should also help program-authors avoid accidentally logging in production (even if it's a no-op, I'm not sure about the guarantees the compiler provides for deleting the extra code).

All `Debug` implementations (custom or derived) should be behind a feature flag. Same goes for any `Debug` trait bounds.

**Comment by iFrostizz** [comment]
I fear that we won't be able to remove it from custom errors, as discussed in https://github.com/dtolnay/thiserror/issues/290
though there is a lot of other constructs which can have their `Debug` implementation behind a `debug` flag
