### ISSUE TITLE
Context should be immutable

### ISSUE THREAD

**Issue by iFrostizz** [ava-labs/hypersdk#1046]
~~Because we still plan to add `value` and some measurement of time and block number~~

edit:
The context should be immutable, thanks to @richardpringle for their comment: https://github.com/ava-labs/hypersdk/issues/1046#issuecomment-2163002283

old title: "Context should be `#[non_exhaustive]`"

**Comment by richardpringle** [comment]
I think it makes more sense to make the fields private and have accessors rather than use the non-exhaustive attribute. `Context` shouldn't have mutable fields in the first place.
