### ISSUE TITLE
Fix Token Wallet build

### ISSUE THREAD

**Issue by joshua-kim** [ava-labs/hypersdk#1125]
Running the token wallet build script outputs:
```
# Building target: darwin/universal

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1048d2eb4]
```

My IDE is also complaining about [this](https://github.com/ava-labs/hypersdk/blob/838307c104f0ae6e01e096b8def704029ad395b5/examples/tokenvm/cmd/token-wallet/main.go#L17) line which references a non-existent directory for goembed.

We should also make sure building the token wallet is reflected in CI. Seems like our CI isn't picking this up.

**Comment by containerman17** [comment]
This might become obsolete in a week or so if we rebuild the frontend for TokenVM. Please hold on.
