### ISSUE TITLE
Decompose VM Controller

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/hypersdk#1159]
The VM Controller `Initialize` function currently takes in a large number of parameters and returns a large number as well:

https://github.com/ava-labs/hypersdk/blob/e4dae2c380b685bb509a3d2858720aa5d6a49843/vm/dependencies.go#L101

This couples together a few pieces of functionality that can be more cleanly separated and made easier to re-use across different VM implementations.

I'd suggest that we break this down into distinct components:

## Genesis/Upgrade + Chain Rules

This suggestion is to remove `genesis/upgrade` from the params passed into the VM and remove `Rules(timestamp) chain.Rules` from the controller interface.

This functionality should be moved out to its own component that's responsible for parsing the `genesis/upgrade` bytes and returning the chain rules as needed given a timestamp.

The current VM implementations already pass this off to their `Genesis` structs.

We can then use a factory injection pattern to replace the current VM constructor that just takes in the controller and a version to take in a genesis factory as well.

This would look like:

```golang
func New() *vm.VM {
	return vm.New(
		genesisFactory{},
		&Controller{},
		version.Version,
	)
}
```

The genesis factory should have an interface to construct a genesis:

```golang
type GenesisFactory interface {
	New(genesisBytes []byte, upgradeBytes []byte) (Genesis, error)
}

type Genesis interface {
	Load(context.Context, avatrace.Tracer, state.Mutable) error

	GetStateBranchFactor() merkledb.BranchFactor

	Rules(timestamp int64, networkID uint32, chainID ids.ID) chain.Rules
}
```

## Builder / Gossiper

Similarly, the controller implementations both pass in a default builder/gossiper implementation already provided by the HyperSDK. The only configurability is used to support a test implementation, which can be handled instead by creating a VM with those test implementations passed in rather than passing a config value into `controller.Initialize` in order to determine which builder/gossiper implementation to use.

This would change roughly from the above into:

```golang
func New() *vm.VM {
	return vm.New(
		genesisFactory{},
		builder.Factory{},
		gossiper.Factory{},
		&Controller{},
		version.Version,
	)
}
```

## Action / Auth Registry + Auth Engine

The action/auth registry are the part that most developers will customize with the current layout of the HyperSDK. Currently, these are registered as constants via `init()` functions and returned directly without modification in the `Initialize` function.

We can push this into the VM constructor as well:

```golang
func New() *vm.VM {
	return vm.New(
		genesisFactory{},
		builder.Factory{},
		gossiper.Factory{},
		consts.ActionRegistry,
		consts.AuthRegistry,
		auth.Engine, // TODO: combine with AuthRegistry?
		&Controller{},
		version.Version,
	)
}
```

## APIs

The APIs are a bit more complicated and are also likely to be customized by most VM developers. The APIs can be broken down into three categories:

- write activity (issue a transaction)
- historical index/state queries
- current state queries

Currently, the controller passes a reference to the current state through the controller, so that it can implement these APIs. To decouple the APIs from the larger controller struct, we can simply pass in an API factory, so that the VM can directly provide a reference to the current state as needed.

To support historical APIs, we could do the same thing where a historical API can register its own `AcceptedSubscriber` as suggested in https://github.com/ava-labs/hypersdk/pull/1143, so that it can maintain its own historical index to serve requests as needed. (note: the HyperSDK aims to push historical indexing out of the VM logic itself as much as possible, so this is slightly frowned upon in the current setup. A better implementation is to push data to an external indexer to handle ingestion and to serve historical APIs separately.)

## After Decomposing the VM

After decomposing the VM into its constituent parts, each example VM should be a good bit smaller and components will be a bit more forcibly decoupled.

For VM developers that want to use all standard components, we can also create a simple helper function that only takes in the Action/Auth/APIs defined by the VM and uses all standard components otherwise.

This is actually a bit more opinionated and less flexible than we should target imo. With these changes, developers will not be able to peal back that layer of abstraction. I think we should clean the current interface up first with these changes and only then work on enabling developers to optionally peal back that layer of abstraction and provide their own components.

**Comment by joshua-kim** [comment]
Related: https://github.com/ava-labs/hypersdk/pull/1188

**Comment by joshua-kim** [comment]
PR to move some dependencies: https://github.com/ava-labs/hypersdk/pull/1192/files
