### ISSUE TITLE
The build script should fail if the simulator fails to build

### ISSUE THREAD

**Issue by iFrostizz** [ava-labs/hypersdk#1174]
There is a warning that shows the error messages from the building of the simulator in the `build.rs` script, but it's not blocking the crate compilation and it may be easy to miss this message and be surprised by changes not taking effect on the simulator.

**Comment by iFrostizz** [comment]
see https://internals.rust-lang.org/t/clearer-display-of-build-script-errors-in-cargo/14222

**Comment by richardpringle** [comment]
> see https://internals.rust-lang.org/t/clearer-display-of-build-script-errors-in-cargo/14222

I'm not sure how this issue really relates to the problem here, especially given that our fix was to simply panic.
