### ISSUE TITLE
Create test package with test helpers

### ISSUE THREAD

**Issue by iFrostizz** [ava-labs/hypersdk#1186]
https://github.com/ava-labs/hypersdk/blob/658b810d65144e2bb6cbe1d71f8d0747e43842fc/examples/morpheusvm/actions/transfer_test.go#L131-L137
The `createAddressWithByte` function should be moved to a dedicated test package that would contain these helpers.

**Comment by aaronbuchwald** [comment]
Duplicate of https://github.com/ava-labs/hypersdk/issues/1187
