### ISSUE TITLE
Generate random address

### ISSUE THREAD

**Issue by RodrigoVillar** [ava-labs/hypersdk#1187]
For testing in HyperSDK, we are using the following function:
```golang
func createAddressWithSameDigits(num uint8) (codec.Address, error) {
	addrSlice := make([]byte, codec.AddressLen)
	for i := range addrSlice {
		addrSlice[i] = num
	}
	return codec.ToAddress(addrSlice)
}
```

Rather, we should have a function `generateRandomAddress()` which produces a randomly-generated address

**Comment by iFrostizz** [comment]
Note that this function should be in a dedicated test package that could be accessed by testing.

**Comment by aaronbuchwald** [comment]
Closed by https://github.com/ava-labs/hypersdk/pull/1255
