### ISSUE TITLE
[x/Programs] Simulator Architecture Research

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#1190]
# Simulator Architecture Research

As noted in #1166, the simulator was initially designed to be a CLI tool and support for rust testing was built as an afterthought on top of the CLI infrastructure. Thus, theres a lot of legacy code that will make it harder to develop, maintain and use(json encodings, piping via I/O, etc). This issue discusses the best way to re-design the simulator. Key design choices being considered are
- maintainability
- developer experience(how easy/intuitive is it for devs to build tests)
- build process(build script, cleaning up run artifacts)
- implementation timeline

## FFI 
This option entails creating a FFI in go that would expose functions rust can use to interact the `runtime` and grab state. 
This is implemented in #1205 and has significantly decreased the maintenance burden by defining a small interface that allows the rust simulator to communicate with the go runtime. This option also gives a lot of control in the future, as we can chose what parts of WASM programs should be written in rust/go. 

## gRPC
This would spin up a gRPC server, clearly define procedures as well as messages such as  `SimulatorResponse` and `SimulatorRequest`. Rust would then call the local gRPC server to interact with the `runtime` and state.

This seems like the easiest interface to call from rust side, and wouldn't cause much overhead in managing state over runtime calls. State could be stored in the servers runtime memory and be erased once the server is killed. 

## Rust Runtime
This options requires re-writing the `wasmtime` in rust. This means our simulator can fully be written in Rust. This offers the simulator all the wonderfulness of rust and allows us to have in-memory state. Moreover could offer performance improvements by taking advantage of the fact `wasmtime` JIT compiler was build using rust.

**Comment by richardpringle** [comment]
>How would state across multiple simulator calls be stored? 

@dboehm-avalabs and I chatted about this a bit. You should be able to have a `State` struct that implements all the interfaces (mutable, view, etc) that is simply instantiated with a few function pointers. Those function pointers can come from the Rust side of the simulator. I'm pretty sure you can even use a function pointer to a closure, though how to do so soundly is less clear. 

In any case, you should essentially be able to inject the state-dependency on instantiation of the cgo wrapper around the runtime. 

Does that make sense?

**Comment by richardpringle** [comment]
>gRPC

Should note that shared types are defined in protobufs. You would still need to spin up the server via Rust, but that should almost be trivial.

**Comment by samliok** [comment]
> @dboehm-avalabs and I chatted about this a bit. You should be able to have a `State` struct that implements all the interfaces (mutable, view, etc) that is simply instantiated with a few function pointers. Those function pointers can come from the Rust side of the simulator. I'm pretty sure you can even use a function pointer to a closure, though how to do so soundly is less clear.

 so essentially you pass in the struct with method pointers through FFI, and then in go you reconstruct that interface by referencing those function pointers.

**Comment by samliok** [comment]
Decided to go with the FFI option as the actual FFI boundary was very minimal. The implementation details can be found here #1205 .
