### ISSUE TITLE
Refactor StateManager: Partition HyperSDK and Application managed state

### ISSUE THREAD

**Issue by joshua-kim** [ava-labs/hypersdk#1218]
It is possible for Action-defined state keys that conflict with VM-defined state keys which can result in the Action/VM overwriting each other and causing unexpected behavior.

Some ideas might be to create separate merkledb instances for the SDK vs the VM, to create a single partitioned merkledb instance that each component has a dedicated prefix for, or to pass a reference to a factory struct where state keys are created from into an Action.

**Comment by aaronbuchwald** [comment]
ref https://github.com/ava-labs/hypersdk/blob/354c5f2cb71ab4bf10f93099ec43bd557dab87a4/chain/dependencies.go#L183

**Comment by joshua-kim** [comment]
Ref: https://github.com/ava-labs/hypersdk/pull/1658
