### ISSUE TITLE
Refactor codec registry + remove consts package

### ISSUE THREAD

**Issue by joshua-kim** [ava-labs/hypersdk#1219]
We have a strange structure in the packages where the codecs aren't even initialized in their own package. Need to move the initialization code to the same place the codecs are defined.

**Comment by aaronbuchwald** [comment]
Note: the intention here is to ensure that the action/auth registries can be imported from any package. We should still get rid of this because it's bizarre that the `consts/` package would require importing a different package to make sure that it's correctly initialized.
