### ISSUE TITLE
Misleading "Golang Environment Misconfigured" error when hawkeye is Missing

### ISSUE THREAD

**Issue by containerman17** [ava-labs/hypersdk#1293]
We use a Rust-based utility called `hawkeye` in `./scripts/fix.lint.sh`. The script includes a function call `check_command hawkeye`, which checks if `hawkeye` is installed:

```bash
function check_command() {
  if ! which "$1" &> /dev/null
  then
      echo -e "\033[0;31myour golang environment is misconfigured...please ensure the golang bin folder is in your PATH\033[0m"
      echo -e "\033[0;31myou can set this for the current terminal session by running \"export PATH=\$PATH:\$(go env GOPATH)/bin\"\033[0m"
      exit
  fi
}
```

Currently, when `hawkeye` is missing, users receive a misleading error message about a misconfigured Golang environment. However, this issue is actually resolved by either running `cargo install hawkeye` or downloading the appropriate binary.

## Proposed Fix

We should update the script to check specifically for `hawkeye` and provide clear instructions on how to install it:

```bash
if ! which "hawkeye" &> /dev/null
then
    echo -e "Hawkeye is not installed. Please install it using 'cargo install hawkeye' or download the binary. Alternatively, you can use the official devcontainer image."
    exit
fi
```

This will prevent confusion and guide users to the correct solution.

**Comment by containerman17** [comment]
Or 
```bash
if ! command -v hawkeye &> /dev/null
then
  echo "hawkeye not found, installing..."
  cargo install hawkeye
fi
```
from `scripts/mock.gen.sh`

**Comment by joshua-kim** [comment]
Fixed in https://github.com/ava-labs/hypersdk/pull/1297
