### ISSUE TITLE
Trailing Newline Character Linter Rule

### ISSUE THREAD

**Issue by containerman17** [ava-labs/hypersdk#1312]
I've received suggestions from @richardpringle and @aaronbuchwald in my PRs to add a trailing newline. To save code reviewers' time, we should set up a linter rule for this. Which file extensions should be covered by this rule?

By the way, why is this important? Most code editors already display empty lines till the end of the screen. My only guess is that it might be related to using the `cat` command.

**Comment by richardpringle** [comment]
It's a lot easier to programmatically add things to a list if the last element of the list includes the separator (which in this case, is a newline character). 

I should just be able to do `echo 'path/to/ignored/file\n' >>  .gitignore`. `vim` will automatically add a newline character to any file that you edit with it. You can configure vscode to do the same. I'm sure most other IDEs also have this feature.

[here are another couple of justifications](https://gist.github.com/OleksiyRudenko/d51388345ea55767b7672307fe35adf3)

**Comment by containerman17** [comment]
I'm closing it for now but will create a PR if it happens frequently in the future. I'll also update my VSCode settings. Thank you for the details, @richardpringle.
