### ISSUE TITLE
Missing a Stable Network Identity for a Dev Net - makes frontend dev much harder

### ISSUE THREAD

**Issue by containerman17** [ava-labs/hypersdk#1316]
Before the major e2e upgrade, which greatly simplified scripts and significantly sped up network launches, we had fixed ports for nodes. Frontend development relied on port 9650. Even if it wasn't 9650, I could request node addresses from ANR. The same applied to the faucet. How can I obtain any node's RPC port number without having to parse the `./scripts/run.sh` output?

**Comment by containerman17** [comment]
```go
  nodes := tmpnet.NewNodesOrPanic(flagVars.NodeCount())
+ nodes[0].Flags["http-port"] = "9650"
  subnet := fixture.NewHyperVMSubnet(
```

^ This helps. I'll do PR after some testing

**Comment by containerman17** [comment]
The only thing left is the blockchain alias. In the previous e2e test system, [it was located here](https://github.com/ava-labs/hypersdk/blob/d78e9305d200190b52f598acf9608686e485ab2f/tests/e2e/e2e.go#L142) under `rpcpb.BlockchainSpec.BlockchainAlias` field as a string.

**Comment by aaronbuchwald** [comment]
Yup, if we need a fixed port, then I'd suggest that we update the default to populate the `http-port` and `chain-aliases-file-content` (https://docs.avax.network/api-reference/avalanche-go-configs-flags#--chain-aliases-file-content-string) to alias the chain. That should give us one node that will always be available at the same URL.

@marun do you have any other suggestion on the best way to make a single URI available for local testing?

**Comment by containerman17** [comment]
When I launch `./scripts/run.sh` for the first time after a stop, it produces the following output:
```
Creating chains for subnet "morpheusvm"
   created chain "22s53YBSbRovg1Ut7WAXoDeWHZF72PNsB1J7dSyiwUVnZnSZ5T" for VM "qCNyZHrs3rZX458wPJXPJJypPf6w423A84jnfbdP2TPEmEE9u" on subnet "morpheusvm"
   wrote chain configuration for subnet "morpheusvm"
```

We need the value `22s53YBSbRovg1Ut7WAXoDeWHZF72PNsB1J7dSyiwUVnZnSZ5T` to create an alias. Currently, I can use this `chainId`, and it works fine.

```bash
curl -X POST http://localhost:9650/ext/bc/2sCdhsxhhzM9ECmRik1CcRaYbtRmxWWR3dqT77MHxGCEnbAZE2y/coreapi -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"hypersdk.network","params":{},"id":1}'

{"jsonrpc":"2.0","result":{"networkId":88888,"subnetId":"6bKr8uSsYVkW1PpZR75zM8yJDVrgV8hCanCqoMikuewq4e6Sn","chainId":"22s53YBSbRovg1Ut7WAXoDeWHZF72PNsB1J7dSyiwUVnZnSZ5T"},"id":1}
```

However, I am trying to figure out how to retrieve this value in `ginkgo.SynchronizedBeforeSuite`. It doesn't seem to be available via `subnet.Chains[0].ChainID`, `consts.ID`, or `subnet.Chains[0].ChainID`.

**Comment by containerman17** [comment]
I'm having trouble with this. GetNetwork is giving me a nil pointer before the network (and nodes) is created. However, as I understand it, I need to fill in `vm-aliases-file-content` before the nodes are created. I could use some help with this.

**Comment by containerman17** [comment]
Thank you, @marun and @aaronbuchwald, for your help! Please take a look at [the PR](https://github.com/ava-labs/hypersdk/pull/1320/files). It includes some questionable solutions, so I'd appreciate your advice.
