### ISSUE TITLE
Should Automatic Marshaling Remove or Retain Size, Marshal, and Unmarshal in the Action Interface?

### ISSUE THREAD

**Issue by containerman17** [ava-labs/hypersdk#1473]
While working on [PR #1198](https://github.com/ava-labs/hypersdk/pull/1198), we faced a choice: With automatic marshaling, we could remove the `Size`, `Marshal`, and `Unmarshal[ActionName]` functions from the `Action` interface. However, these functions might still be necessary for users who want to implement custom marshaling/unmarshaling to potentially achieve higher TPS (even though it's not proven that marshaling is a bottleneck).

The question is, should we be explicit and require users to manually include this code in each action file:

```golang
func (t *Transfer) Size() int {
	size, _ := codec.LinearCodec.Size(t)
	return size
}

func (t *Transfer) Marshal(p *codec.Packer) {
	codec.LinearCodec.MarshalInto(t, p.Packer)
}

func UnmarshalTransfer(p *codec.Packer) (chain.Action, error) {
	var transfer Transfer
	err := codec.LinearCodec.UnmarshalFrom(p.Packer, &transfer)
	return &transfer, err
}
```

Or should we be implicit and hide this behind optional interfaces, so these functions are only used if the user defines them? I’m looking for feedback on the best approach.

🚀 for explicit but redundant code, 🎉 for clean and implicit implementation.

**Comment by HyperPatrick** [comment]
I feel like we should let the user choose whether he wishes to use an automatic unmarshal and marshal function. Most advanced devs would like to be able to set their own marshalling and unmarshalling function in order to reach a desired TPS ( each optimization counts ) whereas this solution can be great for new comers that don't need to worry about this technical part and straight up right their action logic

**Comment by aaronbuchwald** [comment]
I don't think it's the case that most advanced devs will want to set their own marshal/unmarshal functions.

Using a default serialization will enable compatibility with default tooling https://github.com/ava-labs/hypersdk/issues/1197#issue-2428832666. Moreover, serialization is unlikely to be a bottleneck even at high performance: https://github.com/ava-labs/hypersdk/pull/1198#issuecomment-2261788080.

Imo we should keep it until re-implementing DSMR to benchmark and see if it's justified.

**Comment by martineckardt** [comment]
I would def vote for hiding these. We can then in the documentation show a way how this can be customized, but removing all this will massively simplify the action creation.
