### ISSUE TITLE
Consistent Order of Errors

### ISSUE THREAD

**Issue by containerman17** [ava-labs/hypersdk#1536]
We use two approaches for error chaining:

1. The canonical way:
    ```golang
    return fmt.Errorf("failed to initialize block subscription: %w", err)
    ```
2. The reversed order:
    ```golang
    return fmt.Errorf("%w: unable to update last accepted", err)
    ```

I suggest we choose one method and stick to it, preferably the canonical:
`fmt.Errorf("text: %w", err)`

**Comment by aaronbuchwald** [comment]
Let's go with 1
