### ISSUE TITLE
Create an API that enables you to simulate execution of an action and see what state keys it touches.

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/hypersdk#1552]
The `Recorder` struct from the `vmwithcontracts` example should be moved into the core of the hyper-sdk because it's likely useful for _all_ vms.

_Originally posted by @aaronbuchwald in https://github.com/ava-labs/hypersdk/pull/1493#discussion_r1757396124_

**Comment by aaronbuchwald** [comment]
This should be similar to https://github.com/ava-labs/hypersdk/pull/1550 w/ the exception that it will need to execute against a full trie view (support a sequence of dependent R/W operations) rather than using `ReadState` to get an atomic read of the keys specified by `StateKeys`

**Comment by aaronbuchwald** [comment]
This should move https://github.com/ava-labs/hypersdk/blob/77a73baff7574285cb075314f70e7e5bfe05786c/examples/vmwithcontracts/vm/server.go#L99 to be a general purpose call next to https://github.com/ava-labs/hypersdk/blob/77a73baff7574285cb075314f70e7e5bfe05786c/api/jsonrpc/server.go#L174.

Separately, we should update merkledb to smoothly transition the returned immutable state (using last accepted) to using the historical revisions to provide a consistent view that does not get invalidated when a block is accepted.
