### ISSUE TITLE
Change FeeManager to use Getter/Setter Functions

### ISSUE THREAD

**Issue by RodrigoVillar** [ava-labs/hypersdk#1641]
In addition to the title, we would add a `Balance()` method to the JSONRPC API package

**Comment by RodrigoVillar** [comment]
The main bulk of this PR would be modifying `BalanceHandler`.  Currently, we would modify the interface to the following:

```golang
type BalanceHandler interface {
	// StateKeys is a full enumeration of all database keys that could be touched during fee payment
	// by [addr]. This is used to prefetch state and will be used to parallelize execution (making
	// an execution tree is trivial).
	//
	// All keys specified must be suffixed with the number of chunks that could ever be read from that
	// key (formatted as a big-endian uint16). This is used to automatically calculate storage usage.
	SponsorStateKeys(addr codec.Address) state.Keys

	// CanDeduct returns an error if [amount] cannot be paid by [addr].
	CanDeduct(ctx context.Context, addr codec.Address, im state.Immutable, amount uint64) error

	// Deduct removes [amount] from [addr] during transaction execution to pay fees.
	Deduct(ctx context.Context, addr codec.Address, mu state.Mutable, amount uint64) error

	// AddBalance adds [amount] to [addr].
	AddBalance(ctx context.Context, addr codec.Address, mu state.Mutable, amount uint64, createAccount bool) error

        // Balance returns the balance of [addr]
        GetBalance(ctx context.Context, addr codec.Address, im state.Immutable) (uint64, error)
}
```

By adding `GetBalance()`, this would unblock adding a testing framework for `BalanceHandler` (currently, there's no VM-agnostic way for getting the balance of an account). However, since we're already adding a getter function to `BalanceHandler`, we could also go all the way and replace all the setter functions with a single `SetBalance()` function:

```golang
type BalanceHandler interface {
	// StateKeys is a full enumeration of all database keys that could be touched during fee payment
	// by [addr]. This is used to prefetch state and will be used to parallelize execution (making
	// an execution tree is trivial).
	//
	// All keys specified must be suffixed with the number of chunks that could ever be read from that
	// key (formatted as a big-endian uint16). This is used to automatically calculate storage usage.
	SponsorStateKeys(addr codec.Address) state.Keys

        // SetBalance sets the balance of [addr] to [amount]
	SetBalance(ctx context.Context, addr codec.Address, mu state.Mutable, amount uint64, createAccount bool) error

        // Balance returns the balance of [addr]
        GetBalance(ctx context.Context, addr codec.Address, im state.Immutable) (uint64, error)
}
```

The second option would delegate the balance-calculations from HyperSDK itself.

**Comment by richardpringle** [comment]
The getter makes sense. `(Add|Deduct)` _forces_ action-developers to use safe calculations. Depends on how much complexity we want to push onto our users. 

I'll state this again. It would be really helpful to define the optimal HyperSDK user, which would make decisions like this a lot easier.

**Comment by aaronbuchwald** [comment]
`GetBalance` + `SetBalance` makes sense to me, good idea

**Comment by RodrigoVillar** [comment]
@joshua-kim thoughts?

**Comment by joshua-kim** [comment]
> The getter makes sense. (Add|Deduct) forces action-developers to use safe calculations. Depends on how much complexity we want to push onto our users.

I would prefer with keeping `Add` and `Deduct` for this reason. In my mind the user always wants to do a simple add/subtract and so it doesn't make sense to expose more. If users want to arbitrarily modify balances we could have a `Set` and have a static function that helped you get a balance and add a delta to it, but I feel like unless we have a use-case for it at the moment `Add` and `Sub` just seem like a simpler API to use.

**Comment by RodrigoVillar** [comment]
Your first point makes sense and is probably what I'm going to lean towards.

> Also we would have to make whatever new APIs consistent with the current balance api

This is a good point; originally, I was going to follow the EVM way of balance queries (that is, if the account doesn't exist, just return 0 with no error). However, we could also pass in a boolean `accountExists` parameter which, if set to true, makes `GetBalance()` return an error if the account doesn't exist (similar to `createAccount` param in `AddBalace()`)

**Comment by richardpringle** [comment]
What's the benefit of erroring on an account that doesn't exist? Is there an extra cost associated with initializing an account-balance? If no, I can't see any benefit. If yes, providing a `HasBalance` method should suffice for VM-developers who have alternative behaviour when an account hasn't been initialized.

**Comment by aaronbuchwald** [comment]
There is always an `Allocate` cost associated with creating a new account, which is currently enforced by `TState`

**Comment by richardpringle** [comment]
> There is always an `Allocate` cost associated with creating a new account, which is currently enforced by `TState`

If the allocation/cost is enforced/handled by `tstate`, then I don't see any benefit of leaking that information up to the interface in question.
