### ISSUE TITLE
Wrap `PebbleDB` in `CorruptableDB`

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#19]
We should wrap `PebbleDB` in this interface to ensure we never write to a database after receiving an unexpected error (which may lead to unexpected consequences): https://github.com/ava-labs/avalanchego/tree/master/database/corruptabledb

**Comment by rafael-abuawad** [comment]
I'm taking a look, seems interesting, and `ensure we never write to a database after receiving an unexpected error` is a critical part of building rock-solid blockchains. 🔍 👀

**Comment by hexfusion** [comment]
@rafael-abuawad just checking in are you still interested in this work?

**Comment by rafael-abuawad** [comment]
@hexfusion how can this be implemented? I wasn't able to wrap my head around it

**Comment by asadahmedtech** [comment]
@hexfusion ,
Looking into the issue, it seems quite important to prevent writes if the error has happened. 

Just to ensure if the approach is correct for PebbleDb,

1. PebbleDB object implementation maintains `initalError` variable.
2. This field gets updated on every `Write` operation using a `handleError` functionality similar to `corruptableDB`.
3. This field gets checked on every operation on PebbleDB. 

Please let me know if the approach sounds appropriate, then would raise an implementation PR for the same.

**Comment by patrick-ogrady** [comment]
> @hexfusion , Looking into the issue, it seems quite important to prevent writes if the error has happened.
> 
> Just to ensure if the approach is correct for PebbleDb,
> 
> 1. PebbleDB object implementation maintains `initalError` variable.
> 2. This field gets updated on every `Write` operation using a `handleError` functionality similar to `corruptableDB`.
> 3. This field gets checked on every operation on PebbleDB.
> 
> Please let me know if the approach sounds appropriate, then would raise an implementation PR for the same.

IMO we should just wrap any usage of `PebbleDB` (ex: wrap these returned instances: https://github.com/ava-labs/hypersdk/blob/f6588c52f6982dfa0412e7679dd7e6d3006b56ee/storage/storage.go#L57) with AvalancheGo's `CorruptableDB` (https://github.com/ava-labs/avalanchego/tree/638000c42e5361e656ffbc27024026f6d8f67810/database/corruptabledb).

This will automatically handle everything for us. ❤️
