### ISSUE TITLE
Assign TypeID to Actions/Auths Instead of Using Reflect-Based Registry

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#228]
Example:
* https://github.com/ava-labs/hypersdk/blob/96e794f5e65d1fabc110c611a063ec2fca35dd4b/chain/transaction.go#L340-L348

**Comment by najeal** [comment]
@patrick-ogrady please assign it to me

**Comment by patrick-ogrady** [comment]
This should be a fun one 👀
