### ISSUE TITLE
Handle unclean shutdown for accepted block handling (replay?)

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#236]
* https://github.com/ava-labs/hypersdk/blob/96e794f5e65d1fabc110c611a063ec2fca35dd4b/vm/resolutions.go#L160-L164
* https://github.com/ava-labs/hypersdk/blob/96e794f5e65d1fabc110c611a063ec2fca35dd4b/examples/tokenvm/controller/controller.go#L182-L239

This is needed to implement a proper data indexing solution (otherwise gaps may form).

**Comment by aaronbuchwald** [comment]
Replaced by https://github.com/ava-labs/hypersdk/issues/1145
