### ISSUE TITLE
[morpheusvm/tokenvm] move `scripts` to a shared directory

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#263]

**Comment by akp111** [comment]
Hey @patrick-ogrady , can i take it up?

**Comment by akp111** [comment]
thanks @patrick-ogrady . Can you share some details about it?

**Comment by patrick-ogrady** [comment]
We have a number of duplicate scripts in morpheusvm/tokenvm that would be great to generalize and put into the root HyperSDK directory for any Custom VM to use.

**Comment by akp111** [comment]
Hey @patrick-ogrady 
So if I got it correctly, I need to move this https://github.com/ava-labs/hypersdk/tree/main/examples/morpheusvm/scripts
to the root folder? right?

**Comment by patrick-ogrady** [comment]
> Hey @patrick-ogrady So if I got it correctly, I need to move this https://github.com/ava-labs/hypersdk/tree/main/examples/morpheusvm/scripts to the root folder? right?

We want to generalize those scripts and move them to `./scripts` (not just move them). We still need to call them within `morpheusvm` and `tokenvm` but don't want to maintain so much duplicate code.

**Comment by akp111** [comment]
Awesome, thanks a lot for the clarification. Will work on it
