### ISSUE TITLE
Create a simple tutorial on How To Use the HyperSDK 📖

### ISSUE THREAD

**Issue by rafael-abuawad** [ava-labs/hypersdk#33]
Create a simple tutorial on how to use the SDK. I believe this would be the most useful thing. Maybe in written or video form.

Topics that the tutorial should cover:
- **Why?** Why use the HyperSDK
- **How?** How to use it
- **What?** What is the reader/viewer going to build in the tutorial
- **Conclusion** How to expand on it.

**Comment by rafael-abuawad** [comment]
I can work on a written version of the tutorial

**Comment by patrick-ogrady** [comment]
Very curious to see what you come up with!

I think this would be better done by someone other than me because I'm too familiar to know where people would get stuck.

**Comment by rafael-abuawad** [comment]
Sure! I was thinking maybe to create a tutorial on the TokenVM demo that you showed up with Emin last Friday.
