### ISSUE TITLE
How to add a cli function?

### ISSUE THREAD

**Issue by bianyuanop** [ava-labs/hypersdk#362]
I'm adding cli functions in my hypersdk vm project, and i started the project with morpheusvm as template. I met this error after adding one cli function:
_morpheus-cli exited with error: field is not populated: Bytes field is not populated: could not unmarshal action: failed to sign transaction_

Could you help me with this or tell me what's missing to correctly add a cli function?

The cluster is run at background using  ./script/run.sh
The cli tool is built by ./script/build.sh
cli function is tested by ./build/morpheus-cli action upload_entity

my edits:
cli function codes are added here: https://github.com/bianyuanop/oraclevm/blob/main/cmd/morpheus-cli/cmd/action.go#L63
action is registered at registry here: https://github.com/bianyuanop/oraclevm/blob/main/registry/registry.go#L26
the action codes are added here: https://github.com/bianyuanop/oraclevm/blob/main/actions/upload_entity.go

Thanks

**Comment by aphexmunky** [comment]
Have you tried setting https://github.com/bianyuanop/oraclevm/blob/c870572e323d118c18cbcf41c5dde648cab03b93/actions/upload_entity.go#L83 to false

**Comment by bianyuanop** [comment]
Just tried to set `p.UnpackBytes(consts.PayloadMaxLen, false, &upload.Payload)`, but still not working

**Comment by bianyuanop** [comment]
when i tried to directly return an empty upload

```
func UnmarshalUploadEntity(p *codec.Packer, _ *warp.Message) (chain.Action, error) {
	var upload UploadEntity

	// upload.EntityType = p.UnpackUint64(true)
	// upload.EntityIndex = p.UnpackUint64(true)
	// p.UnpackBytes(consts.PayloadMaxLen, false, &upload.Payload)

	return &upload, nil
}
```

it throws another error `morpheus-cli exited with error: failed to decode client response: field is not populated: Uint64 field is not populated: could not unmarshal action: unable to unmarshal on public service  http://127.0.0.1:23676/ext/bc/2p56DQWh87JRh6AWzh1vRD2RjLgRohMDBaXfvKZgi4TeEpghwS/coreapi`

it looks not like the error defined by from me

**Comment by bianyuanop** [comment]
Another question is that do I need to restart the cluster after I edit the `Unmarshal` method of any action? or I can directly rebuild the cli and test again

**Comment by aphexmunky** [comment]
I think the Unmarshal code runs in both the cli and the server so make sure all the processes are dead (the `./scripts/stop.sh` script isn't very effective on my mac), `./scripts/build.sh` and then `./scripts/run.sh`

Your error is likely emitted from here https://github.com/ava-labs/hypersdk/blob/22290eecd4c7106a9ad6678ba84eacd9d3c90eae/codec/packer.go#L90

**Comment by bianyuanop** [comment]
Thanks for help, I successfully worked it out
