### ISSUE TITLE
tokenvm: ./scripts/run.sh: line 142: ginkgo: command not found

### ISSUE THREAD

**Issue by EricForgy** [ava-labs/hypersdk#37]
Not sure how to get past this. This is the same problem I'm having with indexvm

https://github.com/ava-labs/indexvm/issues/17

Any help?

go version go1.19.2 darwin/arm64

**Comment by patrick-ogrady** [comment]
Ahh I should make sure ginkgo is installed in that script. Will add that to the PR.

Thanks for calling out!

**Comment by patrick-ogrady** [comment]
Did some research and I actually do attempt to install `ginkgo` if it doesn't exist:
```bash
go install -v github.com/onsi/ginkgo/v2/ginkgo@v2.1.4
```

Did you remove this line?

**Comment by patrick-ogrady** [comment]
Ah you know what it is...I bet `go/bin` is not in your PATH. I'll error if that occurs.

**Comment by patrick-ogrady** [comment]
I now print this: 
![image](https://user-images.githubusercontent.com/13023275/221313398-cb77fa7b-3169-4f45-9112-b0d14b132350.png)

**Comment by patrick-ogrady** [comment]
this is a common mistake when first getting started with golang.

**Comment by EricForgy** [comment]
You're probably right. This is my first attempt to use Go 😊

Thanks 🙏

**Comment by patrick-ogrady** [comment]
No worries ser 🖖 

Making it easier for everyone that comes after you!
