### ISSUE TITLE
[x/programs] improve dev UX

### ISSUE THREAD

**Issue by hexfusion** [ava-labs/hypersdk#384]
We are making a push to improve the dev UX for programs this issue covers tasks we would like to complete by Friday.

Rust:

- [ ] rename `wasmlanche_sdk` to ?
- [ ] rename all contract to program
- [ ] get all rust crates ready to publish.
- [ ] add ci tooling to allow pushing updates to crates.io, see firewood.
- [ ] add unit tests (lower prio)
- [ ] Dev container?
- [ ] Improve docs
- [ ] Add more ProgramValue variants
- [ ] Finish up TODO's
- [ ] https://doc.rust-lang.org/cargo/reference/profiles.html#overflow-checks
- [ ] `ctx.getSender` call
- [ ] `Maybe` create a [Github template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) with boilerplate for creating a new program.

Golang
- [ ] Improve README and docs
- [ ] Work with devrel on dev container for running VM
- [ ] `getSender` host function
- [ ] Add program simulator which allows developers to test and execute HyperSDK programs
- [ ] Fork Morpheus VM into /x/programs/examples named program VM? (**deferred**)
- [ ] Add basic Ci for VM (**deferred**)
- [ ] Add support for create_program and invoke_program actions (**deferred**)
- [ ] Update client to support ^^ actions (**deferred**)
- [ ] Try to add support for new multi dimension fees (**deferred**)
- [ ] Basic integration test (**deferred**)

**Comment by richardpringle** [comment]
Not sure if this belongs here, but renaming the `expose_macro` crate to `<wasmlanche_sdk>_macros` is a good way to future-proof the existence of other macros (for exporting wrappers for invoking external contracts and the like).

**Comment by richardpringle** [comment]
> Not sure if this belongs here, but renaming the `expose_macro` crate to `<wasmlanche_sdk>_macros` is a good way to future-proof the existence of other macros (for exporting wrappers for invoking external contracts and the like).

^^ no longer relevant

**Comment by samliok** [comment]
still a relevant objective but these are out of date
