### ISSUE TITLE
[chain] Hash Block Based on Hash Trie of Transactions + State Root + Results Root + Warp Outputs Root

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#412]
Otherwise, we'd need to provide all transactions to prove anything about a block.

**Comment by bianyuanop** [comment]
Hey Patrick, 

I'm Chan from NodeKit, I'm taking this with #503. 

I'm curious about that does  **_Hash Block Based on Hash Trie of Transactions + State Root + Results Root + Warp Outputs Root_** mean concatenation of Root of transaction trie with all other roots or it means using a single trie and putting transactions and all other roots in the trie to calculate the root as hash of the block

**Comment by patrick-ogrady** [comment]
Related: #950
