### ISSUE TITLE
[x/programs] Call initialize program in host & pass value to init_program

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#417]
What happens if my code looks like this:
```rust
#[expose]
fn init_program() -> i64 {
    -1
}
```
The program will never work? You may have already replied to my other comment, but it seems like calling the Go function before calling the wasm function would make more sense. You could then return a `bool` or something where `false` causes a revert or whatever.

_Originally posted by @richardpringle in https://github.com/ava-labs/hypersdk/pull/388#discussion_r1305802253_

**Comment by richardpringle** [comment]
@hexfusion, is this still relevant? If we return a `Result` (which I think we're planning on doing?), this issue would definitely be resolved. Please close this issue if that's the case.

**Comment by hexfusion** [comment]
I think we need to re add this flow so lets leave it open for now.

**Comment by richardpringle** [comment]
Closing in favour of #595
