### ISSUE TITLE
[x/programs] Update alloc function to align allocation with memory

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#428]
the alloc function is extremely slow because it doesn't make sure the returned memory is aligned

**Comment by richardpringle** [comment]
@samliok @hexfusion, is this still an issue?

**Comment by richardpringle** [comment]
@samliok, I marked the issue as unassigned because I don't think this is actually in your pipeline, is it? If I'm wrong, please just re-assign yourself. I'm not necessarily ready to pick this one up, but it would be good to easily tell what's open to pick up.

**Comment by richardpringle** [comment]
this is no longer relevant
