### ISSUE TITLE
[x/programs] Deep dive serializer/deserializer for WASM programs 

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#430]
Currently we are using `Serde_bare` to serialize/deserialize bytes.  [https://docs.rs/serde_bare/latest/serde_bare/](url)

This project has a notice stating the encoding is not finalized. 

A deeper dive should be made regarding
- The process for upgrading programs.
- The serialization scheme used for calling other programs (especially across different languages and library versions). 
- Inconsistency across serialization versions 
- `serde_bare` as our current `serializer/deserializer`  
- Investigate these issues with regards to safety and consensus

**Comment by patrick-ogrady** [comment]
Both NEAR and Solana use Borsh: https://borsh.io/

**Comment by patrick-ogrady** [comment]
Let's just use borsh for now
