### ISSUE TITLE
[network] Compress Tx Gossip + State Sync Traffic

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#470]
Optionally Compress AppGossip/AppRequest Traffic

**Comment by StephenButtolph** [comment]
Avalanchego already compresses App messages: 
- https://github.com/ava-labs/avalanchego/blob/master/message/outbound_msg_builder.go#L645
- https://github.com/ava-labs/avalanchego/blob/master/message/outbound_msg_builder.go#L661
- https://github.com/ava-labs/avalanchego/blob/master/message/outbound_msg_builder.go#L676

**Comment by patrick-ogrady** [comment]
well, that was an easy ticket to knock out
