### ISSUE TITLE
[x/programs] Add Program CI

### ISSUE THREAD

**Issue by exdx** [ava-labs/hypersdk#507]
Run programs through simulator in CI on PRs

**Comment by hexfusion** [comment]
To clarify this we do test the program examples in Go[1].

[1] https://github.com/ava-labs/hypersdk/tree/main/x/programs/examples

**Comment by hexfusion** [comment]
This should now be implemented using the VM new simulator via #537

**Comment by richardpringle** [comment]
This is partially complete 
https://github.com/ava-labs/hypersdk/pull/730

I still need to figure out a good process for testing the examples in the most automated way possible.

**Comment by richardpringle** [comment]
Always more work to be done to improve things, but this is definitely solved at a minimum

https://github.com/ava-labs/hypersdk/pull/748 wrapped this one up for now!
