### ISSUE TITLE
[x/programs] Add utility/helper tooling for building Programs

### ISSUE THREAD

**Issue by exdx** [ava-labs/hypersdk#508]
Building a program from scratch is complex and ideally tools should be introduced to simplify the process. Simply copy/pasting from examples is not ideal. 

* Provide a CLI tool that can bootstrap a basic program crate
* The tool can come with presets that produce different program types

**Comment by richardpringle** [comment]
Kind of a dup of #463... or maybe #463 is contained in this issue?
