### ISSUE TITLE
[x/programs] Update self parameter in programs from Program

### ISSUE THREAD

**Issue by exdx** [ava-labs/hypersdk#509]
Currently programs take a `Program` parameter as the first argument. This argument may need to update to reflect something more accurate, for example `Context`. 

```
/// Initializes the program with a name, symbol, and total supply.
#[public]
pub fn init(program: Program) -> bool {
    // set total supply
    program
        .state()
        .store(StateKey::TotalSupply.to_vec(), &123456789)
        .expect("failed to store total supply");
```

**Comment by hexfusion** [comment]
how does `entrypoint` differ from the `public` macro we have?

**Comment by exdx** [comment]
Personally I find it more intuitive

**Comment by exdx** [comment]
But I don't think this issue is regarding the entrypoint -- we just need to figure out what we'd like to call the first argument in program functions

**Comment by hexfusion** [comment]
> Personally I find it more intuitive

Can you elaborate how it is more intuitive? The name or the functionality etc.

**Comment by exdx** [comment]
> > Personally I find it more intuitive
> 
> Can you elaborate how it is more intuitive? The name or the functionality etc.

I think the naming convention is more intuitive, yes. It clearly shows which function starts the program -- basically like `main()` or something. See also the `constructor()` function in solidity -- https://docs.soliditylang.org/en/latest/introduction-to-smart-contracts.html

The public macro is used across all functions in the contract, not just the initialization.

**Comment by hexfusion** [comment]
> > > Personally I find it more intuitive
> > 
> > 
> > Can you elaborate how it is more intuitive? The name or the functionality etc.
> 
> I think the naming convention is more intuitive, yes. It clearly shows which function starts the program -- basically like `main()` or something. See also the `constructor()` function in solidity -- https://docs.soliditylang.org/en/latest/introduction-to-smart-contracts.html
> 
> The public macro is used across all functions in the contract, not just the initialization.

Gotcha they don't serve the same purpose then I suspect, `public` exposes the function as an export, meaning the host can call it. Currently initialization is an optional step and that will be done for free by the runtime if you implement the `init` function as `public`. So all of the init logic must be in a single function.

Probably worth a separate issue around this.

**Comment by richardpringle** [comment]
> My opinion is that self in this case is not a context but instead a reference to the program itself.
> 
> I think this becomes more obvious as you consider for example a program to program call.
> 
> here the caller is self which is a program and the target is also a program. This feels very logical to me.
> 
> https://github.com/ava-labs/hypersdk/blob/7931d011cbeb237a9ea31dcfd1b93be4639ba504/x/programs/rust/wasmlanche_sdk/src/program.rs#L29-L44

🤔, you bring up a very interesting point. Maybe the second argument should always be `ctx`? There may be more things that we want to inject in the future. OR, we could do something like 
```rust
pub struct Program {
    id: /* ... */, 
    ctx: Context, 
}
// where
pub struct Context; // looks like this for now, just a ZST with no functionality 
```

And now that I write that out, the latter seems like the best move. Other thoughts or opinions? @exdx?

**Comment by richardpringle** [comment]
Closing in favour of #707
