### ISSUE TITLE
Add large block support

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#52]
To send blocks larger than 2MB, allow a block to include hashes for other chunks that can be downloaded over the P2P layer before verification (and after parse).

If all chunks can't be received, then the block will simply fail verification.

We should probably do this with some form of erasure coding.

While we could simply just "send more blocks", this allows us to perform fewer merkle root calculations and consensus events.

We will need to be very thoughtful about introducing protection mechanisms so a malicious producer can't force us to fetch a bunch of useless data.

**Comment by rafael-abuawad** [comment]
How can this be implemented efficiently?

**Comment by aaronbuchwald** [comment]
Closing in favor of the Vryx design
