### ISSUE TITLE
[Questions] How do one run the rust program example ?

### ISSUE THREAD

**Issue by Sanghren** [ava-labs/hypersdk#535]
Hello,

As the title says, how can I run [the rust wasm programs](https://github.com/ava-labs/hypersdk/tree/main/x/programs/rust/examples) ?

Looked around but did not see much info about it.

Thanks !

**Comment by Sanghren** [comment]
> > Hello,
> > As the title says, how can I run [the rust wasm programs](https://github.com/ava-labs/hypersdk/tree/main/x/programs/rust/examples) ?
> > Looked around but did not see much info about it.
> > Thanks !
> 
> The rust programs currently can be run as part of a golang test. See the token example[1]. Basically you can drop the compiled Wasm in the testdata/ directory and reference it in your test as the example shows. Compilation steps are here[2].
> 
> But later today I will have a PR up which will provide a VM simulator which will make this process much easier. Will ping you when its up.
> 
> [1] https://github.com/ava-labs/hypersdk/blob/main/x/programs/examples/token_test.go#L35 [2] https://github.com/ava-labs/hypersdk/tree/main/x/programs/rust

Great thanks !

**Comment by patrick-ogrady** [comment]
You can follow along here: #537
