### ISSUE TITLE
[rpc/storage] Allow for optionally storing `block.Results` on-disk for stream replay after restart

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#556]
To offer a production-ready solution, we need to guarantee there won't be a gap in block history, even if there is an unclean shutdown. This means we need to persist the block during `block.Accept` (before updating the last accepted block on-disk and/or committing state).

**Comment by patrick-ogrady** [comment]
We need to decide if we want to utilize the otherwise stored blocks on-disk or to just store the entire message on-disk (in case the block on-disk representation changes).

**Comment by patrick-ogrady** [comment]
> We need to decide if we want to utilize the otherwise stored blocks on-disk or to just store the entire message on-disk (in case the block on-disk representation changes).

We should not assume anything about how the block is stored elsewhere on the node and should store the entire message on-disk separately.

**Comment by manojkgorle** [comment]
Hey, I am working on this issue. I have a few questions.

1) Should `txIDs` be stored along with `block.Results`?

> We need to decide if we want to utilize the otherwise stored blocks on-disk or to just store the entire message on-disk (in case the block on-disk representation changes).

2) what does the *message* here refer to? 

3) should the number of `block.Results` stored be limited? or make it tunable?

I have something in mind: 

- optional storage can be tuned by config params passed during `vm.Initialize`.  

- a new DB instance to store `block.Results`, similar to how blocks are stored.

**Comment by manojkgorle** [comment]
> Hey @patrick-ogrady, should the number of `block.Results` stored be limited to `acceptedBlockWindow`? or make it tunable?

it won't make sense if `block.Results` are stored with out `block` to the disk.

**Comment by patrick-ogrady** [comment]
Related: #961
