### ISSUE TITLE
[chain] Add ability to have Read-Only State Keys

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#561]
This will allow multiple HyperSDK Programs to read the contract code concurrently (which would otherwise be a conflict key and require serial execution -> It should only require serial execution if the code is being modified).

This will also lead to lower "max fees" and is good for the HyperSDK regardless to provide.

**Comment by wlawt** [comment]
@patrick-ogrady we can probably close this issue now right?
