### ISSUE TITLE
[x/programs] Add versioning schema to simulation Plans

### ISSUE THREAD

**Issue by exdx** [ava-labs/hypersdk#568]
Currently there is no versioning for the simulation plans introduced in #567. 

Since the schema will likely change and grow over time, introducing versioning early on is generally considered best practice. 

Possible schema version names:
* v1
* 1
* pragma 1
* v0.0.1

**Comment by richardpringle** [comment]
This doesn't matter right now. We will need versioning eventually though. At that point, we can open a new task
