### ISSUE TITLE
Error loading workspace: You have opened a nested module.

### ISSUE THREAD

**Issue by EricForgy** [ava-labs/hypersdk#58]
This is probably not a big deal, but thought I'd mention it.

I am getting the following warning in VS Code:
```
Error loading workspace: You have opened a nested module. To work on multiple modules at once, 
please use a go.work file. See https://github.com/golang/tools/blob/master/gopls/doc/workspace.md 
for more information on using workspaces.
```

**Comment by patrick-ogrady** [comment]
Hmm not sure what this error is (never ran into it myself). My guess is that it has to do with the min `go1.20` version update: #43
