### ISSUE TITLE
[warp] Support AWM Communication with C-Chain

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#580]
* https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/warp/payload/README.md
* https://github.com/ava-labs/teleporter

**Comment by patrick-ogrady** [comment]
Related: #949

**Comment by aaronbuchwald** [comment]
Closing in favor of https://github.com/ava-labs/hypersdk/issues/949
