### ISSUE TITLE
morpheus-cli hangs during transfer action

### ISSUE THREAD

**Issue by yesil** [ava-labs/hypersdk#603]
I followed examples/morpheusvm/README.md and the token transfer step seems to be hanging constantly.

```
database: .morpheus-cli
address: morpheus1rvzhmceq997zntgvravfagsks6w0ryud3rylh4cdvayry0dl97nsp30ucp
chainID: 2eoHq1wiumDYpBErNHSFE7YV25uwtgBRhH1W6wFdCggkPT5HsS
balance: 9999998999.999975204 RED
recipient: morpheus1fl5nngach956zeng90c0jm9m9c8h499nk5kaz559ld56vskfkreqh74sk6
amount: 10
continue (y/n): y
```

**Comment by patrick-ogrady** [comment]
Were you able to capture any interesting logs during this?

**Comment by yesil** [comment]
I added extra logs, and it seems it is not able to find the txID.

![image](https://github.com/ava-labs/hypersdk/assets/330057/02945796-d4ef-4b4b-b58b-74015150ccfc)

**Comment by patrick-ogrady** [comment]
I figured this out. This is because the default mode in `./scripts/run.sh` no longer keeps a tx index. I need to migrate the CLI to use websockets.

In the meantime, I'll revert this default change and it should work in the next release.

**Comment by patrick-ogrady** [comment]
I decided to rip the bandaid off and just migrate the CLI to use WS. The benefit of this change is that it is WAY faster.
