### ISSUE TITLE
[x/programs]  Deep dive WASM runtime memory

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#605]
I guess I would need to dig into this further but my general understanding is that while technically possible for a pointer to exceed that limit. A 64bit system would not utilize even close to that entire range and a Program which has a capped memory limit via the runtime store/engine is a much smaller subnet of that address space.

I guess what I am saying is there is a trade off between extreme edge case safety and usability/complexity. Its a great topic though and we should try to write some tests to exercise this.

_Originally posted by @hexfusion in https://github.com/ava-labs/hypersdk/pull/600#discussion_r1381677565_

**Comment by hexfusion** [comment]
The runtime explicitly checks a pointer as being sane[1].

[1] https://github.com/ava-labs/hypersdk/blob/main/x/programs/runtime/memory.go#L37

**Comment by richardpringle** [comment]
> The runtime explicitly checks a pointer is sane[1]. So my belief here is that any pointer we pass to the SDK will be pre-checked.
> 
> [1]
> 
> https://github.com/ava-labs/hypersdk/blob/f735d9422ef7db029ec64bb26a2bf9af563dac98/x/programs/runtime/memory.go#L37-L39

@samliok, can we closed this based on the comment above?
