### ISSUE TITLE
[x/programs] Improve communication between host and program

### ISSUE THREAD

**Issue by hexfusion** [ava-labs/hypersdk#622]
This issue is mean to encapsulate an are of focus for the program runtime covering the following topics.

- [ ] Improve `Import` UX by implementing `Caller` and providing useful helper methods.
  - [ ] https://github.com/ava-labs/hypersdk/pull/631
- [ ] Improve linear memory access to use serialization and improve function signature bloat by encoding length and pointer into a single int64.
  - [ ] https://github.com/ava-labs/hypersdk/pull/631 
- [ ] Improve context switching metering and observability (metrics).
  - [ ] https://github.com/ava-labs/hypersdk/issues/519
- [ ] Improve overall testing/coverage.
- [ ] Improve data transfer between client to simulator. Move to a more jsonrpc like model.

**Comment by MuffinsThaCat** [comment]
> * [ ]  Improve `Import` UX by implementing `Caller` and providing useful helper methods.

What is `Caller` doing?

**Comment by hexfusion** [comment]
Caller is basically a wrapper around the `program.Instance` which calling the import function. For now I am providing access to `Export` and `Memory`.

**Comment by hexfusion** [comment]
Caller is basically a wrapper around the `program.Instance` which calling the import function. For now I am providing access to `Export` and `Memory`.

**Comment by richardpringle** [comment]
I think some of the description here is either captured in other issues or lacking detail. I think we can just open other tickets. Thoughts @dboehm-avalabs?

Closing this for now though...
