### ISSUE TITLE
[x/programs] Move from ED25519 public keys to hypersdk addresses

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#634]
Node that Address is 33 bytes. I recommend using `Address` directly here, if possible: https://github.com/ava-labs/hypersdk/blob/283846bac51de111d18c225c8b0a7b92b6cf6ec8/codec/address.go

_Originally posted by @patrick-ogrady in https://github.com/ava-labs/hypersdk/pull/624#discussion_r1412494845_

**Comment by richardpringle** [comment]
@samliok, I think this is done, right? I'm closing it, feel free to re-open if more needs to be done.
