### ISSUE TITLE
[x/programs] Wasmlanche Program Calls

### ISSUE THREAD

**Issue by MuffinsThaCat** [ava-labs/hypersdk#635]
How do I convert the wasmlanche program calls into wasmtime calls?

Example 

 ```
 #[public]
fn initialize_address(program: Program, address: Address) -> bool  
``` 

How would I call that with get_typed_func on a compiled wasm binary?

@hexfusion

**Comment by MuffinsThaCat** [comment]
Few of the links I've been referencing:

https://21-lessons.com/how-to-run-webassembly-from-your-rust-program/

https://users.rust-lang.org/t/calling-a-wasm-method-that-accepts-a-byte-array-with-embedded-wasmtime/57241

**Comment by hexfusion** [comment]
Well `get_typed_func` is part of the rust engine so you would not be using that directly unless you plan on implementing the golang engine in Rust which i would not recommend at this point as many thing are in the process of changing.

To call Rust from Rust you will want to explore the VM simulator. Take a look at this test and follow the logical flow. Then also the Rust Simulator client logic[2].

While not complete the goal of the simulator will be to emulate JSON-RPC client calls to a VM. Still a fair amount of work that needs to be done here to make this cleaner but as soon as we land Borsh as a first class serialization format this will all come together nicely. You can follow @samliok progress on that here. [3]

[1]  https://github.com/ava-labs/hypersdk/blob/main/x/programs/rust/examples/token/src/lib.rs#L137
[2]  https://github.com/ava-labs/hypersdk/blob/main/x/programs/rust/wasmlanche_sdk/src/simulator.rs
[3] https://github.com/ava-labs/hypersdk/pull/623

**Comment by MuffinsThaCat** [comment]
My plan was to use the hosts runtime primarily for enclave creation, signing and attestation. Then to use a separate runtime(written in Rust) for another enclave which would be able to run the unmodified programs in Webassembly. It does seem like they would still be able to share the same engine now.

**Comment by MuffinsThaCat** [comment]
The other consideration I was having was using https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#wit-worlds

Although I'm not sure how far along this is.

**Comment by iFrostizz** [comment]
@MuffinsThaCat if you want an example of interacting with programs via the Rust runtime, you could look at https://github.com/ava-labs/hypersdk/blob/6b2f73eedd7c395b2f7ff8bfbde2fbe45aa26970/x/programs/rust/wasmlanche-sdk/tests/public_function.rs#L13
Please don't hesitate to ask questions or if that is not what you wanted!

**Comment by iFrostizz** [comment]
I'm gonna close this one, open it again if you think that it is relevant.
