### ISSUE TITLE
[x/programs] Programs Library

### ISSUE THREAD

**Issue by MuffinsThaCat** [ava-labs/hypersdk#648]
Having an issue building the programs library with Go:

go: downloading github.com/near/borsh-go v0.3.1
go: downloading github.com/ava-labs/avalanchego v1.10.15
go: downloading go.uber.org/zap v1.24.0
go: downloading github.com/oasisprotocol/curve25519-voi v0.0.0-20230110094441-db37f07504ce
go: downloading github.com/stretchr/testify v1.8.3
go: downloading go.uber.org/mock v0.2.0
go: downloading github.com/bytecodealliance/wasmtime-go/v14 v14.0.0
go: downloading go.uber.org/atomic v1.10.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/crypto v0.14.0
go: downloading golang.org/x/exp v0.0.0-20230626212559-97b1e661b5df
go: downloading golang.org/x/sync v0.3.0
go: downloading golang.org/x/term v0.13.0
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: downloading github.com/btcsuite/btcd/btcutil v1.1.3
go: downloading github.com/prometheus/client_golang v1.16.0
go: downloading go.opentelemetry.io/otel v1.11.2
go: downloading go.opentelemetry.io/otel/trace v1.11.2
go: downloading github.com/mr-tron/base58 v1.2.0
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading gonum.org/v1/gonum v0.11.0
go: downloading google.golang.org/grpc v1.58.3
go: downloading google.golang.org/protobuf v1.31.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.11.2
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.11.2
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.11.2
go: downloading go.opentelemetry.io/otel/sdk v1.11.2
go: downloading golang.org/x/sys v0.13.0
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/prometheus/common v0.42.0
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/prometheus/procfs v0.10.1
go: downloading github.com/google/renameio/v2 v2.0.0
go: downloading go.opentelemetry.io/proto/otlp v0.19.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.11.2
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20230711160842-782d3b101e98
go: downloading github.com/golang/protobuf v1.5.3
go: downloading google.golang.org/genproto v0.0.0-20230711160842-782d3b101e98
go: downloading github.com/DataDog/zstd v1.5.2
go: downloading github.com/go-logr/logr v1.2.3
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.15.2
go: downloading github.com/cenkalti/backoff/v4 v4.2.0
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20230711160842-782d3b101e98
go: downloading golang.org/x/net v0.17.0
go: downloading golang.org/x/text v0.13.0
# runtime/cgo
In file included from _cgo_export.c:3:
/usr/include/stdlib.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
FAIL    github.com/ava-labs/hypersdk/x/programs/examples [build failed]

**Comment by patrick-ogrady** [comment]
AFAICT this happens when your machine is missing some 32-bit libraries: https://github.com/sirfz/tesserocr/issues/130

What OS are you using to build?

**Comment by MuffinsThaCat** [comment]
Thanks that worked! Ubuntu 20.0.4

Can't get the imports to work getting this:

```/runtime_ex.go:28:14: undefined: NewConfigBuilder
./runtime_ex.go:32:13: undefined: New
./runtime_ex.go:32:39: undefined: NoSupportedImports```

**Comment by hexfusion** [comment]
> ./runtime_ex.go
Can you share the code you are using or at least the hypersdk relevant section of go.mod

My assumption is that your dependencies are not correct.

**Comment by MuffinsThaCat** [comment]
It should be the same as this: https://github.com/ava-labs/hypersdk/blob/main/go.mod

Or no?

Was trying to run it in the runtime directory.

This is the test:

package main

import (
	"context"
	"fmt"

	"github.com/ava-labs/avalanchego/utils/logging"
	"github.com/bytecodealliance/wasmtime-go/v14"
)

// /"github.com/ava-labs/hypersdk/x/programs/runtime"
func main() {

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// infinite loop
	wasm, err := wasmtime.Wat2Wasm(`
	(module
	  (func (export "run_guest")
	    (loop
	      br 0)
	  )
	)
	`)
	fmt.Print(err)
	maxUnits := uint64(10000)
	cfg, err := NewConfigBuilder().
		WithLimitMaxMemory(1000000000). // 1 pages
		Build()

	runtime := New(logging.NoLog{}, cfg, NoSupportedImports)
	err = runtime.Initialize(ctx, wasm, maxUnits)

	runtime.Stop()

	_, err = runtime.Call(ctx, "run")

}

Logic and imports are the same as https://github.com/ava-labs/hypersdk/blob/main/x/programs/runtime/runtime_test.go

What testing environment are you using?

**Comment by hexfusion** [comment]
the runtime directory is package `runtime` so the above can not work.

to write the above as a test use the following.

```go
package runtime

import (
	"testing"

	github.com/ava-labs/avalanchego/utils/logging"
       "github.com/bytecodealliance/wasmtime-go/v14"
)

func TestSomething(t *testing.T) {
    // logic
}
```

Then test like so.

```sh
go test -v -timeout 30s -run ^TestSomething$ github.com/ava-labs/hypersdk/x/programs/runtime
```

**Comment by hexfusion** [comment]
> What testing environment are you using?

You can execute the test in a shell but I use vscode as in IDE.

**Comment by MuffinsThaCat** [comment]
It just gives me this "found packages examples (counter_test.go) and main (runtime_ex.go) in /home/ ...     But doesn't actually say that anything is being run. What's the expected output of having run the test?

**Comment by hexfusion** [comment]
For example notice -v flag

```
go test -v -timeout 30s -run ^TestDefaultSerialization$ github.com/ava-labs/hypersdk/x/programs/runtime
=== RUN   TestDefaultSerialization
--- PASS: TestDefaultSerialization (0.00s)
PASS
ok      github.com/ava-labs/hypersdk/x/programs/runtime 0.004s
:~/projects/ava-labs/hypersdk/hypersdk/x/programs$ 
```

**Comment by MuffinsThaCat** [comment]
Mhm. Saw that command in the comments of counter_test.go . The above "found packages examples" was what was returned. What's the TestDefaultSerialization? Maybe I can try that.

**Comment by hexfusion** [comment]
https://github.com/ava-labs/hypersdk/blob/ad3ac9427c178c85cc55e5dbc9b044b04152d89e/x/programs/runtime/config_test.go#L13-L24

**Comment by MuffinsThaCat** [comment]
Tried to run that test and it doesn't work for me. Same response as before.

**Comment by hexfusion** [comment]
My expectation is that golang environment has not been setup correctly. You will need a properly setup go env with CGO support. In general I use gvm[1] to manage this. Once that is complete show the output of `go env`

[1] https://github.com/moovweb/gvm
