### ISSUE TITLE
[x/program] Rename SmartPtr type 

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#649]
Do you want to create an issue to rename this? Smart-pointers are already thing in Rust [^1]. An `Arc` is an example of a smart-pointer. While there are tons of terms that are overloaded, I wouldn't want a new program dev to land in this code for whatever reason and get confused. 

[^1]: https://doc.rust-lang.org/book/ch15-00-smart-pointers.html

_Originally posted by @richardpringle in https://github.com/ava-labs/hypersdk/pull/623#discussion_r1422587446_

Potential names `MemoryPtr`, or `ArgumentPtr`, `ArgPtr`...

**Comment by richardpringle** [comment]
As mentioned offline, I'm good with pretty much any name. `HostPtr` might be another option since that's essentially what we're doing here.
