### ISSUE TITLE
[x/programs] pass error messages from host functions

### ISSUE THREAD

**Issue by samliok** [ava-labs/hypersdk#666]
Currently if our host function throws an error we propagate it up the runtime and stop executing the program.

Defining a common `hostResponse` in the `host` and `guest` would provide a more descriptive error handling framework. A potential struct like this would give us more programability and allow us to better handle different responses in the guest. 

```go
type  MsgLevel  int
const (
	None MsgLevel  =  iota
	Info
	Error
	Panic
)
type hostResponse struct {
	value int64
	level MsgLevel
	message []byte
}
```
the host function would convert a `hostResponse` to a `smartPtr` and then return as `*types.Val` in order to match the required [function signature](https://github.com/ava-labs/hypersdk/pull/660/files#diff-9619b5dfe09284cc8c7bd4374ad3404b91e577f8c3335cb8791cf14fff0ef99bR53). Or it can stop program execution by throwing an `error`.

 For example, the `getFn` host function returns -1 if it [cannot find a key in its db](https://github.com/ava-labs/hypersdk/blob/main/x/programs/examples/imports/pstate/pstate.go#L128). It also returns a -1 if it [cannot grab bytes from memory](https://github.com/ava-labs/hypersdk/blob/main/x/programs/examples/imports/pstate/pstate.go#L110)(a more serious error). These errors are not descriptive. Even with the new refactor of #660, some errors should still be passed to the host while others can stop the runtime.

**Comment by richardpringle** [comment]
Seems like this is linked with #595?

**Comment by richardpringle** [comment]
See specific comment from the above PR here
https://github.com/ava-labs/hypersdk/pull/737#discussion_r1499098482

**Comment by richardpringle** [comment]
Closing this in favour of #595. Host functions (with the exception of external calls) should not return `Result`.
