### ISSUE TITLE
[x/programs] Ability to get the caller ID in the current program context

### ISSUE THREAD

**Issue by iFrostizz** [ava-labs/hypersdk#707]
prob related: https://github.com/ava-labs/hypersdk/issues/509

It would be good to be able to get the caller ID in the context of the current program to be able to implement useful features such as access control, can take this EVM smart contract as a reference: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol
This `context.Context` type borrowed from Go seems very natural as passed as a function argument, but it may not be passed in the `Program` struct because in this case it doesn't make sense to pass a context or being able to write it if we are calling for instance an external program.
Maybe that the definition of the `#[public]` attribute would allow the definition of this `Context` struct which would contain the caller ID as a separate parameter.

**Comment by patrick-ogrady** [comment]
Actions will always be provided an "Actor" (codec.Address) by "Auth", so that should be included in the program context.

We are still solidifying the spec around how callers are managed during cross-program calls.

**Comment by richardpringle** [comment]
@dboehm-avalabs, assigned this to you because I believe #710 resolves this. If it doesn't, please comment and you can unassign yourself (unless you plan on doing it right away haha).

**Comment by iFrostizz** [comment]
https://github.com/ava-labs/hypersdk/pull/1008
