### ISSUE TITLE
[x/programs] Cannot pass two `Program` parameters to a Rust program

### ISSUE THREAD

**Issue by iFrostizz** [ava-labs/hypersdk#713]
It is currently not possible to pass two parameters with the type of `Program` when calling programs written in Rust, which doesn't seem to be a limitation using the Go simulator because it is capable of fully testing problematic function in the counter program. 
This issue makes it impossible to call programs externally in a program with the simulator, e.g

```rust
#[public]
pub fn external_supply(_: Program, token: Program) -> i64 {
    token
        .call_function("get_total_supply", vec![], 10000)
        .unwrap()
}
```

And calling it will result in a `program execution failed: code that was supposed to have been unreachable was reached`

This can be reproduced by modifying the token program with this diff:
[token_lib_rs.patch.txt](https://github.com/ava-labs/hypersdk/files/14184349/token_lib_rs.patch.txt)
also available at this branch: https://github.com/iFrostizz/hypersdk/compare/csamm-example...iFrostizz:hypersdk:fork/double_programs_err

**Comment by richardpringle** [comment]
Hey @iFrostizz, I think #638 will solve this. I'm going to close this. Please re-open if you disagree!
