### ISSUE TITLE
[x/programs] return dynamic data types in output, other than wasm supported data types.

### ISSUE THREAD

**Issue by manojkgorle** [ava-labs/hypersdk#714]
Wasm-supported data types are only used as outputs in wasmlanche_sdk. The outputs are passed to the host and returned by the `tx.Action`.

Instead, it would be better if can pass a pointer to a struct or any data type, packed with the length.
```rust
return ((ptr as u64) << 32) | len as u64;
```

then reading memory of host, to get the bytes and return.

**Comment by richardpringle** [comment]
Thanks @manojkgorle, I'm going to close this issue in favour of the other and will reply to your comment there
