### ISSUE TITLE
[x/progams] Abstract Storage for Program Simulator

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/hypersdk#746]
Right now, it appears as though the simulator is relying on pebble and I'm running into some concurrency issues when trying to run multiple instances of the simulator. We shouldn't need to save anything to disk running the simulator. For more involved integration tests, we can deploy a devnet, or something along those lines.

**Comment by iFrostizz** [comment]
https://github.com/ava-labs/hypersdk/pull/986
