### ISSUE TITLE
[x/programs] Remove the VM from the simulator

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/hypersdk#756]
See @patrick-ogrady's comment here
https://github.com/ava-labs/hypersdk/pull/743#discussion_r1513329516

>I think there is a future where we could rip this out and just stub the host function to the WASM engine? If we did want to provide this "chain" feel, then it would make sense to keep it (but that may be better handled by an actual devnet instance of a VM with the WASM engine).

**Comment by richardpringle** [comment]
@najeal, this could be another interesting issue if you're looking for something. It's blocked on 
 - [ ] https://github.com/ava-labs/hypersdk/pull/743
 - [ ] https://github.com/ava-labs/hypersdk/pull/748
 
 But they should make their way into `main` soon

**Comment by najeal** [comment]
@richardpringle I'm on it as soon as you merge the two PRs 👍

**Comment by richardpringle** [comment]
@najeal, this one's no longer blocked!

**Comment by iFrostizz** [comment]
Closed by https://github.com/ava-labs/hypersdk/pull/1022
