### ISSUE TITLE
[x/programs] Assert that a plan step failed

### ISSUE THREAD

**Issue by iFrostizz** [ava-labs/hypersdk#865]
It would be useful to be able to pass a signed integer to the `require` field in the steps specifying it, this way we could assert that a step failed as expected.
Additionally, the error message when an assertion has failed could be improved with the expected and actual value much like the `assert_eq!` macro in Rust. The error message is currently invariably  `result assertion failed`.

**Comment by najeal** [comment]
What the signed integer is supposed to represent? Hypersdk does not give us information on the Error triggered rust program side, we get a `ErrTrapUnreachableCodeReached` error golang host side.

**Comment by iFrostizz** [comment]
@najeal The -1 number is currently returned on an unsuccessful call, see https://github.com/ava-labs/hypersdk/blob/f002156f55e422c79631904582f77ed0811d7419/x/programs/examples/imports/program/program.go#L85
We are moving the assertions out of the simulator though, so this issue will be closed as part of this rewrite.

**Comment by iFrostizz** [comment]
So we now can do that because the error is caught in the `error` field of the response, but I would like to close this issue once we have faillible responses from external calls for a really complete feature.
