### ISSUE TITLE
[x/programs] call_function should return the deserialized data

### ISSUE THREAD

**Issue by iFrostizz** [ava-labs/hypersdk#871]
The `call_function` currently returns the pointer of the data in memory

https://github.com/ava-labs/hypersdk/blob/76f8132d777ca44687a48e34e09416642dc59564/x/programs/rust/wasmlanche-sdk/src/program.rs#L44

We should probably not expose the pointer on the program but rather deserialize the data as in the `get` method.

**Comment by iFrostizz** [comment]
We could also make it return a bool which would translate the success state of the external call

**Comment by richardpringle** [comment]
I think it should return a pointer. There should be another layer for deserialization. You should be able to conditionally compile a program such that all `#[public]` functions are actually just wrappers around `call_program`, and that's probably where deserialization should be handled.

**Comment by iFrostizz** [comment]
https://github.com/ava-labs/hypersdk/pull/896
