### ISSUE TITLE
[x/programs] Lazily Serialize Params

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/hypersdk#885]
If you look at the `params!` definition here:
https://github.com/ava-labs/hypersdk/blob/3fdf8bfdddd50496e45956efb3de1ca4aa0edb61/x/programs/rust/wasmlanche-sdk/src/params.rs#L7-L13

You can see that each param is serialized eagerly, then all the serialized params are put into a `Vec<Param>`, which is then also serialized into `Params(Vec<u8>)`. But with the changes in this PR, we serialized this _again_  ... it's super inefficient. It kind of made sense before, but it definitely doesn't make sense to do this now. 

I'm thinking that `Params(Vec<u8>)` -> `Vec<Box<dyn BorshSerialize>>` , and serialize it in one shot here:
https://github.com/ava-labs/hypersdk/blob/3fdf8bfdddd50496e45956efb3de1ca4aa0edb61/x/programs/rust/wasmlanche-sdk/src/program.rs#L63

_Originally posted by @richardpringle in https://github.com/ava-labs/hypersdk/pull/881#discussion_r1589622876_

**Comment by iFrostizz** [comment]
https://github.com/ava-labs/hypersdk/pull/954
