### ISSUE TITLE
[x/programs] Serialize/Deserialize ProgramID properly

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/hypersdk#913]
This will be fixed, just setup this way to make the deserialization easier for initial test.

_Originally posted by @dboehm-avalabs in https://github.com/ava-labs/hypersdk/pull/900#discussion_r1601952423_

**Comment by richardpringle** [comment]
@dboehm-avalabs Feel free to close this if it's not relevant

**Comment by dboehm-avalabs** [comment]
Fixed in #917
