### ISSUE TITLE
[x/simulator]: looks broken on main branch

### ISSUE THREAD

**Issue by najeal** [ava-labs/hypersdk#926]
A lot of files have been deleted on `main` broken. It is impossible to build the simulator as it uses not found packages.

**Comment by patrick-ogrady** [comment]
Yeah, it definitely is. We are working on fixing it rn: https://github.com/ava-labs/hypersdk/pull/918

We opted to get some bigger breaking changes into the HyperSDK core and into Programs first (rather than doing a large merge branch).

**Comment by najeal** [comment]
Thank for the information. Just as you said, it looks resolved by the recent merge of #918
