### ISSUE TITLE
[testing] Switch e2e tests from gomega to testify

### ISSUE THREAD

**Issue by marun** [ava-labs/hypersdk#977]
The use of the gomega assertion library for e2e tests and testify for unit tests increases the cost of maintaining the hypersdk tests since developers have to be familiar with both libraries. Switching the e2e tests to testify avoids that problem. 

Note that avalanchego and subnet-evm have already been updated to use testify as their only assertion library.

**Comment by patrick-ogrady** [comment]
As mentioned offline, we should attempt to do this once we get further into the "Developer Ready" milestone (as the changes that will occur there may significantly change the form of the tests).
