### ISSUE TITLE
[ci] Commit to `ginkgo` or replace with `go test`

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#988]
It is unclear if we really need to rely on `ginkgo` for `integration`/`e2e` or if we can get by with out-of-the-box golang testing.

golang testing has come a long way since ginkgo was released (both adding parallelism + subtests): https://onsi.github.io/ginkgo/#why-ginkgo (https://go.dev/blog/subtests)

<img width="840" alt="image" src="https://github.com/ava-labs/hypersdk/assets/13023275/aff8acac-421f-4f5a-98a7-3bd68b388af4">

**Comment by patrick-ogrady** [comment]
In isolation, my view at this moment is that normal go testing is sufficient (with `testify`) but am open to other perspecitves.

**Comment by aaronbuchwald** [comment]
We'll keep ginkgo as the standard for integration/e2e
